# FINANCE DATA
TIME = 'TIME'
OPEN = 'OPEN'
HIGH = 'HIGH'
LOW = 'LOW'
CLOSE = 'CLOSE'
VOL = 'VOL'

EMA = 'EMA'
SMA = 'SMA'
MACD = 'MACD'
MACD_S = 'SIGNAL'
MACD_H = 'HIST'

#BOLLINGER BANDS
BB_UP = 'BB_UP'
BB_MED = 'BB_MED'
BB_LOW = 'BB_LOW'
BB_FACTOR = 1

#RSI
RSI = 'RSI'
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_FACTOR = 1.1

#S_RSI
S_RSI_K = 'S_RSI_K'
S_RSI_D = 'S_RSI_D'
S_RSI_OVERSOLD = 20
S_RSI_OVERBOUGHT = 80

# HTML COLORS
PURPLE = '#cc33ff'
ORANGE = '#ff6600'
BLACK = 'k'
CYAN = 'c'
RED = 'r'
GREEN = 'g'
WHITE = 'w'
BLUE = 'b'